### ISSUE TITLE
Guards on true or false branches

### ISSUE THREAD

**Issue by fcmartins** [pestt/PESTT#25]
1. Generate a graph
2. Select guards only on true branches
3. It shows guards on both branches

If we select guards on false branches, then no guards are shown
instead of being shown on the false branches.

**Comment by ruigameiro** [comment]
This problem occurs in Mac OS because the character encoding is differet.
In Mac OS, Eclipse character encoding by default is MacRoman and the plug-in uses UTF-8.

To change the default character encoding to UTF-8 go to
Eclipse → Window → Preferences→ General → Workspace → Text file encoding → Other and choose UTF-8.
